### ISSUE TITLE
bamsurgeon gives error while adding indels 

### ISSUE THREAD

**Issue by nruthen** [adamewing/bamsurgeon#134]

**Comment by adamewing** [comment]
It looks like this is due to `samtools` not being in your `$PATH`, does the docker image have that installed?

**Comment by nruthen** [comment]
Yes, that was the issue. Samtools is installed, but because of the 
`RUN cp samtools/samtools $HOME /bin line `
in the Dockerfile, `samtools` was not in my `$PATH`. I was able to resolve this issue by finding the path to `samtools` with `ls -lth /root/bin/` and then `PATH=$PATH:/root/bin` to put the directory that contained samtools into my `$PATH`.

**Comment by nruthen** [comment]
I also understand that the error:
************************************************************
encountered error in mutation spikein: 19_21145434_21145435_0.54:INS:-
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addindel.py", line 122, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/mutation.py", line 276, in mutate
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region
AssertionError: Error: could not pile up over region: haplo_19_21145434_21145435
************************************************************
indicates that the BAM files I am using lack coverage over the area I am trying to add mutations but should I be concerned about the warnings: 

WARNING 2019-06-26 13:09:49,047 haplo_11_32417941_32417942 could not pileup for region: 11:32418019
WARNING 2019-06-26 13:09:49,098 haplo_11_32417941_32417942 could not pileup for region: 11:32418020
WARNING 2019-06-26 13:09:49,151 haplo_11_32417941_32417942 could not pileup for region: 11:32418021
WARNING 2019-06-26 13:09:49,204 haplo_11_32417941_32417942 could not pileup for region: 11:32418022
WARNING 2019-06-26 13:09:49,240 haplo_11_32417941_32417942 could not pileup for region: 11:32418023
INFO 2019-06-26 13:09:49,245 11_32417941_32417942_0.17:INS:- len(readlist): 107
INFO 2019-06-26 13:09:49,245 11_32417941_32417942_0.17:INS:- selected VAF: 0.170000
INFO 2019-06-26 13:09:49,246 11_32417941_32417942_0.17:INS:- picked: 18 reads
INFO 2019-06-26 13:09:49,246 11_32417941_32417942_0.17:INS:- wrote: 0, mutated: 18
INFO 2019-06-26 13:09:49,316 19_21145434_21145435_0.54:INS:- creating tmp bam: addindel.tmp/19_21145434_21145435_0.54:INS:-.tmpbam.43830317-1109-4001-9513-fc637202b10a.bam

where it appears to have created output BAM files successfully? Are those output BAM files accessible or were they destroyed following the error message?

**Comment by Rapsssito** [comment]
@nruthen, could you try with the latest commit (not version) and reopen an issue if the issue still persists.
