### ISSUE TITLE
Installation error: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by drZhan** [adamewing/bamsurgeon#135]
I have run `python setup.py build` , but it returned.

Traceback (most recent call last):
  File "/home/garvin/Downloads/bamsurgeon/setup.py", line 89, in <module>
    if not check_bwa(): sys.exit('Dependency problem: bwa >= 0.7.12 not found')
  File "/home/garvin/Downloads/bamsurgeon/setup.py", line 16, in check_bwa
    p = subprocess.Popen(['bwa'], stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I did have bwa, and I dont know why this happened?

**Comment by Cyril9227** [comment]
Make sure everything is in your PATH

**Comment by adamewing** [comment]
Hi, If you start a python interpreter ('python' with no arguments) and enter the following:
```
import subprocess
subprocess.call(['bwa'])
```
Do you get the bwa argument list or an error?

**Comment by drZhan** [comment]
Thanks a lot, I've already solved the problem when I run all of the codes under the root.
