### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by marcogao2019** [adamewing/bamsurgeon#147]
Hi, I got the same errors while run 'addsnv.py -h', 'addindel.py -h', 'addsv.py -h':

Traceback (most recent call last):                                                                                                                                                 File "/home/***/anaconda3/bin/addsnv.py", line 4, in <module>                                                                                                                __import__('pkg_resources').run_script('bamsurgeon==1.2', 'addsnv.py')                                                                                                         File "/home/***/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script                                                                    self.require(requires)[0].run_script(script_name, ns)                                                                                                                          File "/home/***/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1468, in run_script                                                                   script_code = compile(script_text, script_filename, 'exec')                                                                                                                    File "/home/***/anaconda3/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/EGG-INFO/scripts/addsnv.py", line 319                                                         except Exception, e:                                                                                                                                                                             ^                                                                                                                                                            SyntaxError: invalid syntax  

#######################

Traceback (most recent call last):                                                                                                                                                 File "/home/***/anaconda3/bin/addindel.py", line 4, in <module>                                                                                                              __import__('pkg_resources').run_script('bamsurgeon==1.2', 'addindel.py')                                                                                                       File "/home/***/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script                                                                    self.require(requires)[0].run_script(script_name, ns)                                                                                                                          File "/home/***/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1468, in run_script                                                                   script_code = compile(script_text, script_filename, 'exec')                                                                                                                    File "/home/***/anaconda3/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/EGG-INFO/scripts/addindel.py", line 280                                                       except Exception, e:                                                                                                                                                                             ^                                                                                                                                                            SyntaxError: invalid syntax  

#######################

Traceback (most recent call last):                                                                                                                                                 File "/home/***/anaconda3/bin/addsv.py", line 4, in <module>                                                                                                                 __import__('pkg_resources').run_script('bamsurgeon==1.2', 'addsv.py')                                                                                                          File "/home/***/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script                                                                    self.require(requires)[0].run_script(script_name, ns)                                                                                                                          File "/home/***/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1468, in run_script                                                                   script_code = compile(script_text, script_filename, 'exec')                                                                                                                    File "/home/***/anaconda3/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/EGG-INFO/scripts/addsv.py", line 959                                                          except Exception, e:                                                                                                                                                                             ^                                                                                                                                                            SyntaxError: invalid syntax  

Could you give some help with this?
Thanks

**Comment by adamewing** [comment]
Hi, Looks like you're using python 3. Unfortunately bamsurgeon currently requires python 2. Updating this is on the to-do list but in the mean time you'll need an environment with python 2 to run bamsurgeon.

**Comment by marcogao2019** [comment]
Python2 works, thanks.
