### ISSUE TITLE
Error in addsnv.py, "assert maxfrac is not None"

### ISSUE THREAD

**Issue by Federete** [adamewing/bamsurgeon#154]
Hi there, thanks for this tool!

I am getting this error:
`Traceback (most recent call last):
  File "/software/python-3.7.4/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/nfs/users/nfs_f/fa8/.local/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/EGG-INFO/scripts/addsnv.py", line 162, in makemut
  File "/nfs/users/nfs_f/fa8/.local/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/bamsurgeon/mutation.py", line 277, in mutate
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region
AssertionError: Error: could not pile up over region: haplo_1_422400_422401
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs/users/nfs_f/fa8/.local/bin/addsnv.py", line 4, in <module>
    __import__('pkg_resources').run_script('bamsurgeon==1.2', 'addsnv.py')
  File "/software/python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/software/python-3.7.4/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/nfs/users/nfs_f/fa8/.local/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/EGG-INFO/scripts/addsnv.py", line 521, in <module>
  File "/nfs/users/nfs_f/fa8/.local/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/EGG-INFO/scripts/addsnv.py", line 518, in run
  File "/nfs/users/nfs_f/fa8/.local/lib/python3.7/site-packages/bamsurgeon-1.2-py3.7.egg/EGG-INFO/scripts/addsnv.py", line 429, in main
  File "/software/python-3.7.4/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError: Error: could not pile up over region: haplo_1_422400_422401
`

It happened with a couple of bams.
I am running addsnv like this:

`python3 addsnv.py --mindepth 20 -v 100k_random_muts.ok.tsv -r $ref -o $out_bam         --aligner mem -f $bam --picardjar /path/to/picard-tools-1.131/picard.jar -p 1`

I tested picard tools is working properly by running: 
`java -jar /lustre/scratch119/casm/team268im/fa8/bin/picard-tools-1.131/picard.jar SamToFastq`
(as suggested in another reply).

Any idea what's wrong?

Many thanks!
Federico

**Comment by adamewing** [comment]
Hi Federico, can you confirm whether the input .bam file has coverage over the site in question (1:422400-422401)?

**Comment by Federete** [comment]
Hi Adam. ahh, that's it. I didn't know the sites had to have coverage, thought that was controlled by --mindepth. Thank you!

**Comment by adamewing** [comment]
Ah, yes you're right that it really should handle this more gracefully.
