### ISSUE TITLE
sequence not present

### ISSUE THREAD

**Issue by frankMusacchia** [adamewing/bamsurgeon#177]
Hello,
I have ubuntu20 which has some issues installing python modules. Hence I prepared a singularity container with bamsurgeon and any dependency needed.

I am trying to put an exon deletion within a BAM file. My deletions.bed file is the following:

21 48063447 48063551 0.0 DEL

But I am getting this weird error running my command:

singularity run --bind /media/francesco/  bamsurgeon_container.sif addindel.py -f NA06984.bam -r ucsc.hg19.fasta -v deletions.bed  -o NA06984_deleted.bam

INFO 2021-02-18 10:09:33,515 starting /usr/local/bin/addindel.py called with args: /usr/local/bin/addindel.py -f NA06984.bam -r ucsc.hg19.fasta -v deletions.bed -o NA06984_deleted.bam
INFO 2021-02-18 10:09:33,657 21_48063447_48063551_0.0:DEL creating tmp bam: addindel.tmp/21_48063447_48063551_0.0:DEL.tmpbam.27d13164-74d7-45a4-adb6-4722367e1d56.bam
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/bamsurgeon-1.2-py3.6.egg/EGG-INFO/scripts/addindel.py", line 122, in makemut
  File "/usr/local/lib/python3.6/dist-packages/bamsurgeon-1.2-py3.6.egg/bamsurgeon/mutation.py", line 192, in mutate
    refbase = reffile.fetch(chrom, pcol.pos-1, pcol.pos)
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence '21' not present"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/addindel.py", line 4, in <module>
    __import__('pkg_resources').run_script('bamsurgeon==1.2', 'addindel.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/bamsurgeon-1.2-py3.6.egg/EGG-INFO/scripts/addindel.py", line 439, in <module>
  File "/usr/local/lib/python3.6/dist-packages/bamsurgeon-1.2-py3.6.egg/EGG-INFO/scripts/addindel.py", line 436, in run
  File "/usr/local/lib/python3.6/dist-packages/bamsurgeon-1.2-py3.6.egg/EGG-INFO/scripts/addindel.py", line 345, in main
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: "sequence '21' not present"

Could you help me?
Thanks

**Comment by adamewing** [comment]
Sorry for the delay, in case you're still having this problem, this is probably a mismatch between the chromosome names used in the either the .bam or the input mutation file and the chromosome names used in the reference. Youre reference chromosome names are probably prefixed with 'chr' and my guess is the chromosome names in either the .bam or the input mutation file do not.
