### ISSUE TITLE
local variable 'tmpoutbamname' referenced before assignment

### ISSUE THREAD

**Issue by YanaHrytsenko** [adamewing/bamsurgeon#180]
Hello, 
I
I try running addsnv.py using the following command but I get these errors:
`addsnv.py --aligner mem --seed 1234 --numsnvs 5 --single \
    --varfile random_snvs.txt \
    --bamfile AFR_LWK_1_female_NA19019.bam \
    --reference GRCh38_full_analysis_set_plus_decoy_hla.fa \
    --outbam AFR_LWK_1_female_NA19019_w_added_snv_muts.bam \
    --cnvfile test_cnvlist.txt.gz \
    --picardjar $EBROOTPICARD/picard.jar`

`INFO 2021-05-24 19:50:48,277 starting /opt/software/BAMSurgeon/1.2-GCC-8.3.0-Python-2.7.16/bin/addsnv.py called with args: /opt/software/BAMSurgeon/1.2-GCC-8.3.0-Python-2.7.16/bin/addsnv.py --aligner mem --seed 1234 --numsnvs 5 --single --varfile random_snvs.txt --bamfile AFR_LWK_1_female_NA19019.bam --reference GRCh38_full_analysis_set_plus_decoy_hla.fa --outbam AFR_LWK_1_female_NA19019_w_added_snv_muts.bam --cnvfile test_cnvlist.txt.gz --picardjar /opt/software/picard/2.18.27-Java-1.8/picard.jar
INFO 2021-05-24 19:50:48,748 created tmp directory: addsnv.tmp
INFO 2021-05-24 19:50:48,809 created directory: addsnv_logs_AFR_LWK_1_female_NA19019_w_added_snv_muts.bam
************************************************************
ERROR	2021-05-24 19:50:48.934530	encountered error in mutation spikein: ['22_33714964_33714965_0.5_None']
Traceback (most recent call last):
  File "/opt/software/BAMSurgeon/1.2-GCC-8.3.0-Python-2.7.16/bin/addsnv.py", line 153, in makemut
    cnv = pysam.Tabixfile(args.cnvfile, 'r')
  File "pysam/libctabix.pyx", line 351, in pysam.libctabix.TabixFile.__cinit__
  File "pysam/libctabix.pyx", line 404, in pysam.libctabix.TabixFile._open
  File "pysam/libchtslib.pyx", line 518, in pysam.libchtslib.HTSFile.tell
**NotImplementedError: seek not implemented in files compressed by method 1**
************************************************************
Traceback (most recent call last):
  File "/opt/software/BAMSurgeon/1.2-GCC-8.3.0-Python-2.7.16/bin/addsnv.py", line 520, in <module>
    run()
  File "/opt/software/BAMSurgeon/1.2-GCC-8.3.0-Python-2.7.16/bin/addsnv.py", line 517, in run
    main(args)
  File "/opt/software/BAMSurgeon/1.2-GCC-8.3.0-Python-2.7.16/bin/addsnv.py", line 441, in main
    tmpbamlist = result.get()
  File "/opt/software/Python/2.7.16-GCCcore-8.3.0/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
**UnboundLocalError: local variable 'tmpoutbamname' referenced before assignment**`
Also, is it correct to use --single for assembled WGS?
Any help would be highly appreciated.
Thank you.

**Comment by YanaHrytsenko** [comment]
It was pysam and bgzip issue
