### ISSUE TITLE
ValueError: invalid contig `22` addindel.py failed.

### ISSUE THREAD

**Issue by shiying1595** [adamewing/bamsurgeon#187]
Report an error with my own data experiment  chr22:
Traceback (most recent call last):
  File "/work/bamsurgeon-master/venv/bin/addindel.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/work/bamsurgeon-master/bin/addindel.py", line 439, in <module>
    run()
  File "/work/bamsurgeon-master/bin/addindel.py", line 436, in run
    main(args)
  File "/work/bamsurgeon-master/bin/addindel.py", line 345, in main
    tmpbamlist = result.get()
  File "/home/user/anaconda3/envs/tensorflow/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: invalid contig `22`
addindel.py failed.

**Comment by Rapsssito** [comment]
Make sure you are using the same contig notation in your BAM files and your FASTA fiels, i.e: `chr22` or `22`.

**Comment by Rapsssito** [comment]
Closed due to inactivity.
