### ISSUE TITLE
Error when trying to spike in snvs

### ISSUE THREAD

**Issue by danielecook** [adamewing/bamsurgeon#29]
I am getting the following error

```
ERROR	2015-08-20 12:26:54.730689	encountered error in mutation spikein: ['II_36327_36327_None_None']
Traceback (most recent call last):
  File "bamsurgeon/addsnv.py", line 155, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "/Users/dancook/Documents/git/variant-caller-analysis/bamsurgeon/bs/mutation.py", line 212, in mutate
    return False, hasSNP, maxfrac, outreads, mutreads, mutmates # todo: convert to class
UnboundLocalError: local variable 'maxfrac' referenced before assignment
```

Any idea what the cause might be?

**Comment by adamewing** [comment]
[I pushed a change just now] (https://github.com/adamewing/bamsurgeon/commit/8700ae70d1cc8e9041570ec128803e4b7ff7b581) which will hopefully throw a more helpful error message; my guess is there is no pileup for that region in your BAM. If you're still not able to get it working and you're able to send me more information about the site, please send the mutation input file, the log file, and if possible a BAM snip immediately surrounding the mutation you're trying to make and I'll have a look.

**Comment by danielecook** [comment]
Thanks - I took a look, and this error is resolved. Now I am seeing this:

```
ERROR	2015-09-18 10:11:50.057724	encountered error in mutation spikein: ['X_14674227_14674227_1.0_None']
Traceback (most recent call last):
  File "bamsurgeon/addsnv.py", line 155, in makemut
    mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
  File "/lscr2/andersenlab/dec211/variant-caller-analysis/bamsurgeon/bs/mutation.py", line 214, in mutate
    assert maxfrac is not None, "Error: %s: could not pile up over region: %s" % (mutid, region)
UnboundLocalError: local variable 'mutid' referenced before assignment
```

It doesn't look like mutid is referenced in that function.

**Comment by danielecook** [comment]
I was able to resolve this issue.
