### ISSUE TITLE
Error when trying to mark affected reads

### ISSUE THREAD

**Issue by danielecook** [adamewing/bamsurgeon#30]
Here is another error I am getting when trying to mark affected reads (`--tagreads`) using the addsnv.py script

```
Traceback (most recent call last):
  File "bamsurgeon/addsnv.py", line 467, in <module>
    run()
  File "bamsurgeon/addsnv.py", line 464, in run
    main(args)
  File "bamsurgeon/addsnv.py", line 421, in main
    markreads(mergedtmp, tmp_tag_bam)
NameError: global name 'mergedtmp' is not defined
```

**Comment by adamewing** [comment]
--tagreads looks broken, will fix ASAP.

**Comment by adamewing** [comment]
--tagreads should work properly now.
