### ISSUE TITLE
alignment sanity check failed

### ISSUE THREAD

**Issue by parlar** [adamewing/bamsurgeon#42]
Not sure what's going on here.. see error msg below.  The error seems to be ```bam readcount < fastq readcount```. 

For info: the bam file is based on Haloplex, i.e. an amplicon strategy. Coverage in the area where the variant is introduced is ~2000x. The tested position sits directly at the end of one amplicon (of several) that overlaps it. 

Any suggestions are greatly appreciated.

//Pär

```
[genetik@v01s979 simulBAM]$ run_addsnv.pl test.bed 1-11-ready.bam
INFO	2016-02-02 09:17:37.074275	starting /usr/bin/addsnv.py called with args: /usr/bin/addsnv.py -v test.bed -f 1-11-ready.bam -r /home/genetik/bcbio/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa --aligner mem --picardjar /home/genetik/Downloads/bamsurgeon/picard/picard-tools-1.131/picard.jar -o test.bed.bam

Debug, haploclusters:[[{'start': 25880412, 'end': 25880412, 'chrom': 'chr1', 'altbase': None, 'vaf': None}]]
INFO	2016-02-02 09:17:37.116624	haplo_chr1_25880412_25880412	creating tmp bam:  addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam
WARN	2016-02-02 09:17:37.134438	haplo_chr1_25880412_25880413	could not pileup for region: chr1:25880316
INFO	2016-02-02 09:17:52.464997	haplo_chr1_25880412_25880412	len(readlist): 1998
INFO	2016-02-02 09:17:52.466797	haplo_chr1_25880412_25880412	selected VAF: 0.5

INFO	2016-02-02 09:17:52.471142	haplo_chr1_25880412_25880412	picked: 1000
INFO	2016-02-02 09:17:52.599467	haplo_chr1_25880412_25880412	wrote:  1998 mutated: 1000
INFO	2016-02-02 09:17:52.608542	haplo_chr1_25880412_25880412	converting addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam to fastq

INFO	2016-02-02 09:17:52.608865	converting BAM addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam to FASTQ
[Tue Feb 02 09:17:52 CET 2016] picard.sam.SamToFastq INPUT=addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam FASTQ=addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.fastq INTERLEAVE=true INCLUDE_NON_PRIMARY_ALIGNMENTS=false VALIDATION_STRINGENCY=SILENT    OUTPUT_PER_RG=false RG_TAG=PU RE_REVERSE=true INCLUDE_NON_PF_READS=false READ1_TRIM=0 READ2_TRIM=0 VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Tue Feb 02 09:17:52 CET 2016] Executing as genetik@v01s979.vll.se on Linux 3.10.0-327.4.4.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_65-b17; Picard version: 1.131(cd60f90fdca902499c70a4472b6162ef37f919ce_1431022382) IntelDeflater
[Tue Feb 02 09:17:53 CET 2016] picard.sam.SamToFastq done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2022178816
INFO	2016-02-02 09:17:53.192863	haplo_chr1_25880412_25880412	aligning addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.fastq with bwa mem

[E::bwa_idx_load_from_disk] fail to locate the index files
INFO	2016-02-02 09:17:53.197474	haplo_chr1_25880412_25880412	writing addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam.realign.sam to BAM...
INFO	2016-02-02 09:17:53.202247	haplo_chr1_25880412_25880412	deleting SAM: addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam.realign.sam
INFO	2016-02-02 09:17:53.202353	haplo_chr1_25880412_25880412	sorting output: samtools sort -@ 1 -m 10000000000 -T addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam.realign.sorted.bam -o addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam.realign.sorted.bam addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam
INFO	2016-02-02 09:17:53.207738	haplo_chr1_25880412_25880412	remove original bam:addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam
INFO	2016-02-02 09:17:53.207860	haplo_chr1_25880412_25880412	rename sorted bam: addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam.realign.sorted.bam to original name: addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam
INFO	2016-02-02 09:17:53.208120	haplo_chr1_25880412_25880412	indexing: samtools index addsnv.tmp/haplo_chr1_25880412_25880412.tmpbam.4999c452-32be-47c6-a4a4-e352ca495201.bam
************************************************************
ERROR	2016-02-02 09:17:53.215854	encountered error in mutation spikein: ['chr1_25880412_25880412_None_None']
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 275, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 58, in remap_bam
    remap_bwamem_bam(bamfn, threads, fastaref, picardjar, mutid=mutid, paired=paired)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 195, in remap_bwamem_bam
    raise ValueError("ERROR\t" + now() + "\t" + mutid + "\tbam readcount < fastq readcount, alignment sanity check failed!\n")
ValueError: ERROR	2016-02-02 09:17:53.215762	haplo_chr1_25880412_25880412	bam readcount < fastq readcount, alignment sanity check failed!

************************************************************
INFO	2016-02-02 09:17:53.233485	no succesful mutations
```

**Comment by tdelhomme** [comment]
a solution would be to comment the line in aligners.py (corresponding to your aligner) which generate an error 
```
raise ValueError("ERROR\t" + now() + "\t" + mutid + "\tbam readcount < fastq readcount ... 
```
This is not optimal but you can print in the standard output the difference of counts and then decide if it is sufficiently low. 
It could be better than automatically crash...

**Comment by adamewing** [comment]
How big is your test BAM? Any chance you could send it to me along with the command line and input (-v)?

**Comment by parlar** [comment]
Hi, 

Fast response! I realized that it might be because the reference fasta I used only had an faidx index (not a bwa index). I'm creating this index now.  

The bam is small (~200mb), if the problem persists I'm very grateful for any help I can get. I can put the bam on my gdrive. Thanks!
