### ISSUE TITLE
invalid bam output

### ISSUE THREAD

**Issue by parlar** [adamewing/bamsurgeon#43]
Hi again,

Got it to work, bamsurgeon now outputs a bam file. The problem was indeed the missing index (https://github.com/adamewing/bamsurgeon/issues/42). However, a new problem has now emerged.

When I try to open the bam in igv or with picard's validator, things fail with this error message:

```java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.String```

samtools quickcheck however does not find any problems.

(I have sorted and indexed the bam file).

Is this something that you have seen before?

**Comment by adamewing** [comment]
I haven't and I run BS BAMs through picard/IGV pretty often ... do those tools work with the pre-spikein BAM? What versions of picard/igv are you using?

**Comment by parlar** [comment]
picard-tools-1.131 and IGV_2.3.68

Yes, the pre-spikein bam works fine in igv.

Just noticed that picard (or some portion of) seems integrated into igv, which might explain things. According to the error msg.

The complete error msg in igv is:

```
ERROR [2016-02-02 14:33:29,232]  [AlignmentTileLoader.java:258] [pool-1-thread-9]  Error loading alignment data
java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.String
	at org.broad.igv.sam.PicardAlignment.<init>(PicardAlignment.java:98)
	at org.broad.igv.sam.reader.WrappedIterator.next(WrappedIterator.java:53)
	at org.broad.igv.sam.reader.WrappedIterator.next(WrappedIterator.java:36)
	at org.broad.igv.sam.AlignmentTileLoader.loadTile(AlignmentTileLoader.java:151)
	at org.broad.igv.sam.AlignmentDataManager.loadInterval(AlignmentDataManager.java:352)
	at org.broad.igv.sam.AlignmentDataManager$1.run(AlignmentDataManager.java:318)
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
INFO [2016-02-02 14:33:29,234]  [MessageUtils.java:74] [pool-1-thread-9]  <html>Error encountered querying alignments: java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.String
```

**Comment by adamewing** [comment]
Can you try running the script in scripts/postprocess.py on the spike-in bam and let me know if the result ing 'postprocessed' bam is read by the picard parser?

**Comment by parlar** [comment]
Yes, now it works. I'm enclosing the complete output from the postprocess.py script below. Igv opens the output bam.

Does this make it clear to you what the problem was? It seems to do a lot of fixing. I can try to run it also on the pre-spikein bam file, to compare.


```
[genetik@v01s979 simulBAM]$ /home/genetik/Downloads/bamsurgeon/bamsurgeon/scripts/postprocess.py -f /home/genetik/bcbio/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa.fai -t 10 test.bed.sorted.bam 
INFO	2016-02-02 15:04:14.178224	outputting status every 72960 reads (1%) ...
processed	72960	reads:	72960	paired	0	unpaired	72960	written	36396	mates found.
fixed strand:	12	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	12	fixed mate ref:	0	fixed tlen:	0
processed	145920	reads:	145920	paired	0	unpaired	145920	written	72867	mates found.
fixed strand:	20	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	22	fixed mate ref:	0	fixed tlen:	0
processed	218880	reads:	218880	paired	0	unpaired	218880	written	109066	mates found.
fixed strand:	27	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	31	fixed mate ref:	0	fixed tlen:	0
processed	291840	reads:	291840	paired	0	unpaired	291840	written	145711	mates found.
fixed strand:	46	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	55	fixed mate ref:	0	fixed tlen:	0
processed	364800	reads:	364800	paired	0	unpaired	364800	written	182201	mates found.
fixed strand:	63	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	74	fixed mate ref:	0	fixed tlen:	0
processed	437760	reads:	437760	paired	0	unpaired	437760	written	218680	mates found.
fixed strand:	75	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	89	fixed mate ref:	0	fixed tlen:	0
processed	510720	reads:	510720	paired	0	unpaired	510720	written	255244	mates found.
fixed strand:	97	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	112	fixed mate ref:	0	fixed tlen:	0
processed	583680	reads:	583680	paired	0	unpaired	583680	written	291661	mates found.
fixed strand:	112	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	131	fixed mate ref:	0	fixed tlen:	0
processed	656640	reads:	656640	paired	0	unpaired	656640	written	328110	mates found.
fixed strand:	131	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	152	fixed mate ref:	0	fixed tlen:	0
processed	729600	reads:	729600	paired	0	unpaired	729600	written	364600	mates found.
fixed strand:	141	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	162	fixed mate ref:	0	fixed tlen:	0
processed	802560	reads:	802560	paired	0	unpaired	802560	written	400838	mates found.
fixed strand:	144	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	165	fixed mate ref:	0	fixed tlen:	0
processed	875520	reads:	875520	paired	0	unpaired	875520	written	437416	mates found.
fixed strand:	150	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	171	fixed mate ref:	0	fixed tlen:	0
processed	948480	reads:	948480	paired	0	unpaired	948480	written	474046	mates found.
fixed strand:	157	fixed RG pair:	0	fixed mate pos:	0
fixed unmapped flag:	179	fixed mate ref:	0	fixed tlen:	0
processed	1021440	reads:	1021440	paired	0	unpaired	1021440	written	510036	mates found.
fixed strand:	566	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	192	fixed mate ref:	0	fixed tlen:	0
processed	1094400	reads:	1094400	paired	0	unpaired	1094400	written	546303	mates found.
fixed strand:	570	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	196	fixed mate ref:	0	fixed tlen:	0
processed	1167360	reads:	1167360	paired	0	unpaired	1167360	written	582868	mates found.
fixed strand:	574	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	200	fixed mate ref:	0	fixed tlen:	0
processed	1240320	reads:	1240320	paired	0	unpaired	1240320	written	619393	mates found.
fixed strand:	575	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	201	fixed mate ref:	0	fixed tlen:	0
processed	1313280	reads:	1313280	paired	0	unpaired	1313280	written	655903	mates found.
fixed strand:	579	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	205	fixed mate ref:	0	fixed tlen:	0
processed	1386240	reads:	1386240	paired	0	unpaired	1386240	written	692204	mates found.
fixed strand:	581	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	207	fixed mate ref:	0	fixed tlen:	0
processed	1459200	reads:	1459200	paired	0	unpaired	1459200	written	728739	mates found.
fixed strand:	585	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	211	fixed mate ref:	0	fixed tlen:	0
processed	1532160	reads:	1532160	paired	0	unpaired	1532160	written	765195	mates found.
fixed strand:	588	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	214	fixed mate ref:	0	fixed tlen:	0
processed	1605120	reads:	1605120	paired	0	unpaired	1605120	written	801419	mates found.
fixed strand:	591	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	219	fixed mate ref:	0	fixed tlen:	0
processed	1678080	reads:	1678080	paired	0	unpaired	1678080	written	838200	mates found.
fixed strand:	595	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	223	fixed mate ref:	0	fixed tlen:	0
processed	1751040	reads:	1751040	paired	0	unpaired	1751040	written	874669	mates found.
fixed strand:	597	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	225	fixed mate ref:	0	fixed tlen:	0
processed	1824000	reads:	1824000	paired	0	unpaired	1824000	written	911171	mates found.
fixed strand:	600	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	228	fixed mate ref:	0	fixed tlen:	0
processed	1896960	reads:	1896960	paired	0	unpaired	1896960	written	947123	mates found.
fixed strand:	602	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	231	fixed mate ref:	0	fixed tlen:	0
processed	1969920	reads:	1969920	paired	0	unpaired	1969920	written	984126	mates found.
fixed strand:	604	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	233	fixed mate ref:	0	fixed tlen:	0
processed	2042880	reads:	2042880	paired	0	unpaired	2042880	written	1020559	mates found.
fixed strand:	615	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	247	fixed mate ref:	0	fixed tlen:	0
processed	2115840	reads:	2115840	paired	0	unpaired	2115840	written	1056890	mates found.
fixed strand:	634	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	269	fixed mate ref:	0	fixed tlen:	0
processed	2188800	reads:	2188800	paired	0	unpaired	2188800	written	1093511	mates found.
fixed strand:	648	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	284	fixed mate ref:	0	fixed tlen:	0
processed	2261760	reads:	2261760	paired	0	unpaired	2261760	written	1129715	mates found.
fixed strand:	663	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	301	fixed mate ref:	0	fixed tlen:	0
processed	2334720	reads:	2334720	paired	0	unpaired	2334720	written	1166288	mates found.
fixed strand:	681	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	324	fixed mate ref:	0	fixed tlen:	0
processed	2407680	reads:	2407680	paired	0	unpaired	2407680	written	1202773	mates found.
fixed strand:	696	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	345	fixed mate ref:	0	fixed tlen:	0
processed	2480640	reads:	2480640	paired	0	unpaired	2480640	written	1239042	mates found.
fixed strand:	718	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	370	fixed mate ref:	0	fixed tlen:	0
processed	2553600	reads:	2553600	paired	0	unpaired	2553600	written	1275686	mates found.
fixed strand:	729	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	384	fixed mate ref:	0	fixed tlen:	0
processed	2626560	reads:	2626560	paired	0	unpaired	2626560	written	1312377	mates found.
fixed strand:	739	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	396	fixed mate ref:	0	fixed tlen:	0
processed	2699520	reads:	2699520	paired	0	unpaired	2699520	written	1348832	mates found.
fixed strand:	749	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	409	fixed mate ref:	0	fixed tlen:	0
processed	2772480	reads:	2772480	paired	0	unpaired	2772480	written	1385301	mates found.
fixed strand:	762	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	424	fixed mate ref:	0	fixed tlen:	0
processed	2845440	reads:	2845440	paired	0	unpaired	2845440	written	1421762	mates found.
fixed strand:	767	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	429	fixed mate ref:	0	fixed tlen:	0
processed	2918400	reads:	2918400	paired	0	unpaired	2918400	written	1458262	mates found.
fixed strand:	787	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	452	fixed mate ref:	0	fixed tlen:	0
processed	2991360	reads:	2991360	paired	0	unpaired	2991360	written	1494169	mates found.
fixed strand:	790	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	456	fixed mate ref:	0	fixed tlen:	0
processed	3064320	reads:	3064320	paired	0	unpaired	3064320	written	1531020	mates found.
fixed strand:	803	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	472	fixed mate ref:	0	fixed tlen:	0
processed	3137280	reads:	3137280	paired	0	unpaired	3137280	written	1567590	mates found.
fixed strand:	814	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	484	fixed mate ref:	0	fixed tlen:	0
processed	3210240	reads:	3210240	paired	0	unpaired	3210240	written	1604133	mates found.
fixed strand:	818	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	488	fixed mate ref:	0	fixed tlen:	0
processed	3283200	reads:	3283200	paired	0	unpaired	3283200	written	1640387	mates found.
fixed strand:	829	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	500	fixed mate ref:	0	fixed tlen:	0
processed	3356160	reads:	3356160	paired	0	unpaired	3356160	written	1676819	mates found.
fixed strand:	842	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	514	fixed mate ref:	0	fixed tlen:	0
processed	3429120	reads:	3429120	paired	0	unpaired	3429120	written	1713337	mates found.
fixed strand:	852	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	528	fixed mate ref:	0	fixed tlen:	0
processed	3502080	reads:	3502080	paired	0	unpaired	3502080	written	1749812	mates found.
fixed strand:	873	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	553	fixed mate ref:	0	fixed tlen:	0
processed	3575040	reads:	3575040	paired	0	unpaired	3575040	written	1786452	mates found.
fixed strand:	883	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	565	fixed mate ref:	0	fixed tlen:	0
processed	3648000	reads:	3648000	paired	0	unpaired	3648000	written	1822725	mates found.
fixed strand:	890	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	573	fixed mate ref:	0	fixed tlen:	0
processed	3720960	reads:	3720960	paired	0	unpaired	3720960	written	1859273	mates found.
fixed strand:	902	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	588	fixed mate ref:	0	fixed tlen:	0
processed	3793920	reads:	3793920	paired	0	unpaired	3793920	written	1895840	mates found.
fixed strand:	913	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	600	fixed mate ref:	0	fixed tlen:	0
processed	3866880	reads:	3866880	paired	0	unpaired	3866880	written	1932170	mates found.
fixed strand:	924	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	615	fixed mate ref:	0	fixed tlen:	0
processed	3939840	reads:	3939840	paired	0	unpaired	3939840	written	1968473	mates found.
fixed strand:	943	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	636	fixed mate ref:	0	fixed tlen:	0
processed	4012800	reads:	4012800	paired	0	unpaired	4012800	written	2005151	mates found.
fixed strand:	955	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	650	fixed mate ref:	0	fixed tlen:	0
processed	4085760	reads:	4085760	paired	0	unpaired	4085760	written	2041604	mates found.
fixed strand:	960	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	655	fixed mate ref:	0	fixed tlen:	0
processed	4158720	reads:	4158720	paired	0	unpaired	4158720	written	2077824	mates found.
fixed strand:	963	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	658	fixed mate ref:	0	fixed tlen:	0
processed	4231680	reads:	4231680	paired	0	unpaired	4231680	written	2114649	mates found.
fixed strand:	977	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	674	fixed mate ref:	0	fixed tlen:	0
processed	4304640	reads:	4304640	paired	0	unpaired	4304640	written	2151161	mates found.
fixed strand:	989	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	689	fixed mate ref:	0	fixed tlen:	0
processed	4377600	reads:	4377600	paired	0	unpaired	4377600	written	2187370	mates found.
fixed strand:	991	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	692	fixed mate ref:	0	fixed tlen:	0
processed	4450560	reads:	4450560	paired	0	unpaired	4450560	written	2223853	mates found.
fixed strand:	994	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	695	fixed mate ref:	0	fixed tlen:	0
processed	4523520	reads:	4523520	paired	0	unpaired	4523520	written	2260537	mates found.
fixed strand:	999	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	700	fixed mate ref:	0	fixed tlen:	0
processed	4596480	reads:	4596480	paired	0	unpaired	4596480	written	2296957	mates found.
fixed strand:	1011	fixed RG pair:	0	fixed mate pos:	397
fixed unmapped flag:	712	fixed mate ref:	0	fixed tlen:	0
processed	4669440	reads:	4669440	paired	0	unpaired	4669440	written	2333355	mates found.
fixed strand:	1016	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	717	fixed mate ref:	0	fixed tlen:	0
processed	4742400	reads:	4742400	paired	0	unpaired	4742400	written	2369927	mates found.
fixed strand:	1028	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	730	fixed mate ref:	0	fixed tlen:	0
processed	4815360	reads:	4815360	paired	0	unpaired	4815360	written	2406346	mates found.
fixed strand:	1029	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	732	fixed mate ref:	0	fixed tlen:	0
processed	4888320	reads:	4888320	paired	0	unpaired	4888320	written	2442718	mates found.
fixed strand:	1040	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	747	fixed mate ref:	0	fixed tlen:	0
processed	4961280	reads:	4961280	paired	0	unpaired	4961280	written	2479071	mates found.
fixed strand:	1048	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	755	fixed mate ref:	0	fixed tlen:	0
processed	5034240	reads:	5034240	paired	0	unpaired	5034240	written	2515938	mates found.
fixed strand:	1055	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	766	fixed mate ref:	0	fixed tlen:	0
processed	5107200	reads:	5107200	paired	0	unpaired	5107200	written	2552077	mates found.
fixed strand:	1064	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	778	fixed mate ref:	0	fixed tlen:	0
processed	5180160	reads:	5180160	paired	0	unpaired	5180160	written	2588781	mates found.
fixed strand:	1066	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	780	fixed mate ref:	0	fixed tlen:	0
processed	5253120	reads:	5253120	paired	0	unpaired	5253120	written	2625222	mates found.
fixed strand:	1069	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	783	fixed mate ref:	0	fixed tlen:	0
processed	5326080	reads:	5326080	paired	0	unpaired	5326080	written	2661726	mates found.
fixed strand:	1074	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	791	fixed mate ref:	0	fixed tlen:	0
processed	5399040	reads:	5399040	paired	0	unpaired	5399040	written	2698149	mates found.
fixed strand:	1084	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	802	fixed mate ref:	0	fixed tlen:	0
processed	5472000	reads:	5472000	paired	0	unpaired	5472000	written	2734726	mates found.
fixed strand:	1103	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	824	fixed mate ref:	0	fixed tlen:	0
processed	5544960	reads:	5544960	paired	0	unpaired	5544960	written	2771146	mates found.
fixed strand:	1120	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	842	fixed mate ref:	0	fixed tlen:	0
processed	5617920	reads:	5617920	paired	0	unpaired	5617920	written	2807662	mates found.
fixed strand:	1130	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	853	fixed mate ref:	0	fixed tlen:	0
processed	5690880	reads:	5690880	paired	0	unpaired	5690880	written	2844152	mates found.
fixed strand:	1133	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	857	fixed mate ref:	0	fixed tlen:	0
processed	5763840	reads:	5763840	paired	0	unpaired	5763840	written	2880040	mates found.
fixed strand:	1139	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	864	fixed mate ref:	0	fixed tlen:	0
processed	5836800	reads:	5836800	paired	0	unpaired	5836800	written	2917181	mates found.
fixed strand:	1145	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	871	fixed mate ref:	0	fixed tlen:	0
processed	5909760	reads:	5909760	paired	0	unpaired	5909760	written	2953527	mates found.
fixed strand:	1150	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	876	fixed mate ref:	0	fixed tlen:	0
processed	5982720	reads:	5982720	paired	0	unpaired	5982720	written	2989849	mates found.
fixed strand:	1153	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	879	fixed mate ref:	0	fixed tlen:	0
processed	6055680	reads:	6055680	paired	0	unpaired	6055680	written	3026435	mates found.
fixed strand:	1156	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	882	fixed mate ref:	0	fixed tlen:	0
processed	6128640	reads:	6128640	paired	0	unpaired	6128640	written	3063052	mates found.
fixed strand:	1164	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	892	fixed mate ref:	0	fixed tlen:	0
processed	6201600	reads:	6201600	paired	0	unpaired	6201600	written	3099399	mates found.
fixed strand:	1180	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	909	fixed mate ref:	0	fixed tlen:	0
processed	6274560	reads:	6274560	paired	0	unpaired	6274560	written	3135929	mates found.
fixed strand:	1196	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	926	fixed mate ref:	0	fixed tlen:	0
processed	6347520	reads:	6347520	paired	0	unpaired	6347520	written	3172486	mates found.
fixed strand:	1207	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	939	fixed mate ref:	0	fixed tlen:	0
processed	6420480	reads:	6420480	paired	0	unpaired	6420480	written	3208833	mates found.
fixed strand:	1224	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	961	fixed mate ref:	0	fixed tlen:	0
processed	6493440	reads:	6493440	paired	0	unpaired	6493440	written	3245374	mates found.
fixed strand:	1235	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	973	fixed mate ref:	0	fixed tlen:	0
processed	6566400	reads:	6566400	paired	0	unpaired	6566400	written	3281983	mates found.
fixed strand:	1238	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	976	fixed mate ref:	0	fixed tlen:	0
processed	6639360	reads:	6639360	paired	0	unpaired	6639360	written	3318469	mates found.
fixed strand:	1242	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	980	fixed mate ref:	0	fixed tlen:	0
processed	6712320	reads:	6712320	paired	0	unpaired	6712320	written	3354571	mates found.
fixed strand:	1249	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	988	fixed mate ref:	0	fixed tlen:	0
processed	6785280	reads:	6785280	paired	0	unpaired	6785280	written	3391308	mates found.
fixed strand:	1252	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	991	fixed mate ref:	0	fixed tlen:	0
processed	6858240	reads:	6858240	paired	0	unpaired	6858240	written	3427846	mates found.
fixed strand:	1260	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	1001	fixed mate ref:	0	fixed tlen:	0
processed	6931200	reads:	6931200	paired	0	unpaired	6931200	written	3464380	mates found.
fixed strand:	1265	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	1008	fixed mate ref:	0	fixed tlen:	0
processed	7004160	reads:	7004160	paired	0	unpaired	7004160	written	3500722	mates found.
fixed strand:	1272	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	1019	fixed mate ref:	0	fixed tlen:	0
processed	7077120	reads:	7077120	paired	0	unpaired	7077120	written	3537233	mates found.
fixed strand:	1276	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	1024	fixed mate ref:	0	fixed tlen:	0
processed	7150080	reads:	7150080	paired	0	unpaired	7150080	written	3573701	mates found.
fixed strand:	1281	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	1029	fixed mate ref:	0	fixed tlen:	0
processed	7223040	reads:	7223040	paired	0	unpaired	7223040	written	3610254	mates found.
fixed strand:	1296	fixed RG pair:	0	fixed mate pos:	398
fixed unmapped flag:	1046	fixed mate ref:	0	fixed tlen:	0
processed	7296000	reads:	7296000	paired	0	unpaired	7296000	written	3646801	mates found.
fixed strand:	1310	fixed RG pair:	0	fixed mate pos:	408
fixed unmapped flag:	1050	fixed mate ref:	0	fixed tlen:	0
WARNING:	2016-02-02 15:10:02.018674	found 2397 orphaned paired reads that were not output!
test.bed.sorted.postprocessed.sam --> test.bed.sorted.postprocessed.bam: samtools view -bt /home/genetik/bcbio/share/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa.fai -o test.bed.sorted.postprocessed.bam test.bed.sorted.postprocessed.sam
test.bed.sorted.postprocessed.bam --> test.bed.sorted.postprocessed.sorted.bam.bam: samtools sort -m 4G -@ 10 -T test.bed.sorted.postprocessed.sorted.bam -o test.bed.sorted.postprocessed.sorted.bam test.bed.sorted.postprocessed.bam
```

**Comment by adamewing** [comment]
Not specifically, but looks like I'd recommend running it on the output BAMs for your application ...  given that the java error was something about casting chars to strings my guess is there's an auxiliary tag in your input BAM that didn't carry over correctly for some reason. Just a guess though, if you're able to share the BAM I could maybe look further.

**Comment by parlar** [comment]
Thanks,. The bam was generated using the bcbio-nextgen pipeline. I'm sending a link by email for the bam files (pre and post spikein) as well as the bed.
