### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by zhmz90** [adamewing/bamsurgeon#46]
The error message is:
```
ERROR	2016-03-30 18:05:41.418927	encountered error in mutation spikein: ['chr1_11169752_11169752_0.53_None']
Traceback (most recent call last):
  File "/home/guo/anaconda/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 274, in makemut
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 58, in remap_bam
    remap_bwamem_bam(bamfn, threads, fastaref, picardjar, mutid=mutid, paired=paired)
  File "build/bdist.linux-x86_64/egg/bamsurgeon/aligners.py", line 154, in remap_bwamem_bam
    fastq = bamtofastq(bamfn, picardjar, threads=threads, paired=paired)[0]
  File "build/bdist.linux-x86_64/egg/bamsurgeon/common.py", line 116, in bamtofastq
    assert os.path.exists(outfq) # conversion failed
AssertionError
```

My VarFile is:
```
chr1    11169752        11169752        0.53
chr1    11187075        11187075        0.503
chr1    11188125        11188125        0.735
chr1    11217241        11217241        0.548
chr1    11298593        11298593        0.898
chr1    11303201        11303201        0.651
chr1    11316087        11316087        0.659
chr1    20945016        20945016        0.53
chr1    26231164        26231164        0.875
chr1    65301817        65301817        0.616
chr1    65323420        65323420        0.518
chr1    65332561        65332561        0.809
chr1    97981456        97981456        0.557
chr1    115252279       115252279       0.59
chr1    144923733       144923733       0.563
```

My cmd is:
```
addsnv.py -v $varfile -f $bamfile -r $ref -p 1 -o $outbam --requirepaired --aligner mem --alignopts t:10 --picardjar /tools/GATK/picard\
/picard-1.119.jar
```

**Comment by adamewing** [comment]
This suggests a bam-->fastq conversion isn't happening which suggests "/tools/GATK/picard/picard-1.119.jar" may not be running properly - could you test manually with:
` java -jar /tools/GATK/picard/picard-1.119.jar SamToFastq`
and let me know if that helps.

**Comment by zhmz90** [comment]
```
java -jar /tools/GATK/picard/picard-1.119.jar SamToFastq

no main manifest attribute, in /tools/GATK/picard/picard-1.119.jar
```
It seems the picard jar does not work.

Thanks  for your time.

**Comment by adamewing** [comment]
OK, will close this then, let me know if anything else goes wrong.

**Comment by zhmz90** [comment]
A new error message:
```
WARN	2016-03-30 21:33:16.071308	chr8_38282156_38282156_0.502_None	depth at site is greater than cutoff, aborting mutation.
ERROR	2016-03-30 21:32:35.344524	encountered error in mutation spikein: ['chr7_98557008_98557008_0.894_None']
Traceback (most recent call last):
  File "/home/guo/anaconda/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 155, in makemut
ValueError: need more than 5 values to unpack

```

The 155th line in `addsnv.py`:
```
        mutfail, hasSNP, maxfrac, outreads, mutreads, mutmates = mutation.mutate(args, log, bamfile, bammate, chrom, min(mutpos_list), max(mutpos_list)+1, mutpos_list, avoid=avoid, mutid_list=\
mutid_list, is_snv=True, mutbase_list=mutbase_list, reffile=reffile)
```


Related code in bamsurgeon/bamsurgeon/mutation.py:

```
                        if len(mutreads) > int(args.maxdepth):
                            sys.stderr.write("WARN\t" + now() + "\t" + mutid + "\tdepth at site is greater than cutoff, aborting mutation.\n")
                            return True, False, {}, {}, {}

```

```
    assert maxfrac is not None, "Error: could not pile up over region: %s" % region

    return False, hasSNP, maxfrac, outreads, mutreads, mutmates # todo: convert to class 
```

**Comment by adamewing** [comment]
Thanks, should be fixed in the latest commit. If you want to spike-in at that location you can increase the value of --maxdepth.
