### ISSUE TITLE
Error in evaluator.py

### ISSUE THREAD

**Issue by mozack** [adamewing/bamsurgeon#72]
Hi,

When running evaluator.py on a Strelka generated VCF, I am getting the following:

python ~/bamsurgeon/bamsurgeon/scripts/evaluator.py -v passed.somatic.indels.vcf -t ../synthetic.challenge.set5.tumour.truth.30pctmasked.vcf.gz -m INDEL
Traceback (most recent call last):
  File "/home/lmose/bamsurgeon/bamsurgeon/scripts/evaluator.py", line 330, in <module>
    main(args)
  File "/home/lmose/bamsurgeon/bamsurgeon/scripts/evaluator.py", line 313, in main
    debug=args.debug)
  File "/home/lmose/bamsurgeon/bamsurgeon/scripts/evaluator.py", line 183, in evaluate
    truvcfh = vcf.Reader(filename=truth)
  File "/usr/lib64/python2.7/site-packages/PyVCF-0.6.0-py2.7-linux-x86_64.egg/vcf/parser.py", line 216, in __init__
    self._parse_metainfo()
  File "/usr/lib64/python2.7/site-packages/PyVCF-0.6.0-py2.7-linux-x86_64.egg/vcf/parser.py", line 254, in _parse_metainfo
    key, val = parser.read_meta(line.strip())
  File "/usr/lib64/python2.7/site-packages/PyVCF-0.6.0-py2.7-linux-x86_64.egg/vcf/parser.py", line 166, in read_meta
    return self.read_meta_hash(meta_string)
  File "/usr/lib64/python2.7/site-packages/PyVCF-0.6.0-py2.7-linux-x86_64.egg/vcf/parser.py", line 161, in read_meta_hash
    val = dict(item.split("=") for item in hashItems)
ValueError: dictionary update sequence element #4 has length 71; 2 is required

Any idea as to what I'm doing wrong here?  I'm running against the bamsurgeon code checked out today.  The truth set is from the Dream Challenge 5.

**Comment by adamewing** [comment]
It looks like PyVCF isn't parsing your VCF properly. Have a look at the header in your VCF and make sure there's nothing unusual (hard to be more specific, sorry). If you like you can email me the VCF at adam.ewing@gmail.com.

**Comment by adamewing** [comment]
Possible PyVCF version issue?

**Comment by mozack** [comment]
Yes, upgrading to the latest version resolved this.  Thanks!
