### ISSUE TITLE
List index out of range 

### ISSUE THREAD

**Issue by biorelated** [adamewing/bamsurgeon#90]
Any one come across this issue? Am I doing something wrong or forgetting a parameter? 

`Python 2.7.8`

I

```
> NFO	2017-04-19 16:18:41.211532	starting /apps/python/2.7.8/bin/addsnv.py called with args: /apps/python/2.7.8/bin/addsnv.py -v mutations/simulated.variants.csv -f /simulated_sequences/sorted_bam/SIM_sample1.sorted.bam -r 9465113.fa -o mutations/sample1_snv
> 
> Traceback (most recent call last):
>   File "/apps/python/2.7.8/bin/addsnv.py", line 4, in <module>
>     __import__('pkg_resources').run_script('bamsurgeon==1.0', 'addsnv.py')
>   File "/apps/python/2.7.8/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/apps/python/2.7.8/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1674, in run_script
>     exec(script_code, namespace, namespace)
>   File "/apps/python/2.7.8/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 513, in <module>
> 
>   File "/apps/python/2.7.8/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 510, in run
> 
>   File "/apps/python/2.7.8/lib/python2.7/site-packages/bamsurgeon-1.0-py2.7.egg/EGG-INFO/scripts/addsnv.py", line 372, in main
> 
> IndexError: list index out of range
```

**Comment by adamewing** [comment]
Make sure you are able to get through the install instructions as described here: https://github.com/adamewing/bamsurgeon/blob/master/README.md

If installed properly, addsnv.py should be in your path so just run:
`addsnv.py -v mutations/simulated.variants.csv -f /simulated_sequences/sorted_bam/SIM_sample1.sorted.bam -r 9465113.fa -o mutations/sample1_snv.bam`

Let me know if that helps.

**Comment by biorelated** [comment]
Yes I followed the instructions as outlined.  There was an issue with the input file format.
