### ISSUE TITLE
Permission Error trying to create semaphore 

### ISSUE THREAD

**Issue by brianhill11** [adamewing/bamsurgeon#94]
Hi, 

I'm getting an error trying to run bamsurgeon on a cluster where I do not have permission to create a semaphore in shared memory. Machines are running CentOS 6.8. 

Command:
```
python ~/code/github/bamsurgeon/bin/addsnv.py -v /u/home/s/serghei/project/EC_survey/S1b/test.bed -f /u/home/s/serghei/project/1000G/subset_24/WGS_cram/test.bam -r /u/home/s/serghei/project/Homo_sapiens/igenomes/genome.fa -o test.txt
```

Output: 
> INFO    2017-05-28 12:32:35.693196      starting  /u/home/b/blhill/code/github/bamsurgeon/bin/addsnv.py called with args: /u/home/b/blhill/code/github/bamsurgeon/bin/addsnv.py -v /u/home/s/serghei/project/EC_survey/S1b/test.bed -f /u/home/s/serghei/project/1000G/subset_24/WGS_cram/test.bam -r /u/home/s/serghei/project/Homo_sapiens/igenomes/genome.fa -o test.txt`

>INFO    2017-05-28 12:32:35.789229      created tmp directory: addsnv.tmp
INFO    2017-05-28 12:32:35.790275      created directory: addsnv_logs_test.txt
Traceback (most recent call last):
  File "/u/home/b/blhill/code/github/bamsurgeon/bin/addsnv.py", line 513, in <module>
    run()
  File "/u/home/b/blhill/code/github/bamsurgeon/bin/addsnv.py", line 510, in run
    main(args)
  File "/u/home/b/blhill/code/github/bamsurgeon/bin/addsnv.py", line 362, in main
    pool = Pool(processes=int(args.procs))
  File "/u/local/apps/python/2.7.2/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/u/local/apps/python/2.7.2/lib/python2.7/multiprocessing/pool.py", line 115, in __init__
    self._setup_queues()
  File "/u/local/apps/python/2.7.2/lib/python2.7/multiprocessing/pool.py", line 208, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/u/local/apps/python/2.7.2/lib/python2.7/multiprocessing/queues.py", line 354, in __init__
    self._rlock = Lock()
  File "/u/local/apps/python/2.7.2/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/u/local/apps/python/2.7.2/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

Is there currently any way to direct the code to not use a semaphore? As the default number of processes is 1, would there be a way to not use a semaphore unless there are multiple processes? 

Thanks,
Brian

**Comment by adamewing** [comment]
Hi Brian,

It doesn't explicitly use semaphores but it looks like this is part of initialising the pool of processes for the multiprocessing module. If you have no way to get around this limitation I suppose you could try modifying it to run single-threaded, for example:

https://github.com/adamewing/bamsurgeon/blob/master/bin/addsnv.py#L428-L439 could be changed to:

`
for hc in haploclusters:
    results.append(makemut(args, hc, avoid, alignopts))

for result in results:
    tmpbamlist = result
    if tmpbamlist is not None:
        for tmpbam in tmpbamlist:
            if os.path.exists(tmpbam):
                tmpbams.append(tmpbam)
`

**Comment by brianhill11** [comment]
Hi Adam, 

Your suggestion works just as I had hoped. Thanks for the help!
